version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: leo
      MONGO_INITDB_ROOT_PASSWORD: cmcx100pre
    ports:
      - 5002:27017
